name:                   Check style

on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - v*
    paths-ignore:
      - 'README.md'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
jobs:
## Check stage
  check-fmt:
    name:                          Check RustFmt
    runs-on:                       ubuntu-latest
    env:
      RUST_BACKTRACE:   full
    steps:
      - name:           Checkout sources & submodules
        uses:           actions/checkout@master
        with:
          fetch-depth:  5
          submodules:   recursive
      - name:           Add rustfmt
        run:            rustup component add rustfmt
      - name:           rust-fmt check
        uses:           actions-rs/cargo@master
        with:
          command:      fmt
          args:         --all -- --check --config merge_imports=true
